name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2"]

    steps:

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: prepare
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          VERSION=php${{ matrix.php }}

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.prepare.outputs.IMAGE_ID }}:${{ steps.prepare.outputs.VERSION }},${{ steps.prepare.outputs.IMAGE_ID }}:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
